event: # в секундах
  interval: 3600 # 1 час
events: #список эвентов в их порядке (для SchedulerImpl)
  - raid
  - airship
  - hellhound
  - arena
messages: ### SCHEDULER MESSAGES
  scheduler-disabled:
    enable: true
    text:
      - ' &cПланировщик событий в данный момент остановлен.'
  scheduler-empty:
    enable: true
    text:
      - ' &cВ очереди нет запланированных событий.'
  scheduler-error-null:
    enable: true
    text:
      - ' &cОшибка: следующее событие повреждено (null).'

  # Когда событие уже идет
  scheduler-info-running:
    enable: true
    text:
      - ' '
      - '  %design_clr_primary%Сейчас идет событие!'
      - '  %design_clr_primary%До следующего (%design_clr_main%{next_event}%design_clr_primary%): &b{time} сек.'
      - ' '

  # Когда сервер просто ожидает запуска следующего события
  scheduler-info-waiting:
    enable: true
    text:
      - ' '
      - '  %design_clr_primary%Следующее событие (%design_clr_main%{next_event}%design_clr_primary%) начнется через: &b{time} сек.'
      - ' '