
bossbar: '&f« %design_clr_main%рейд %design_clr_primary%- коорды: %design_clr_main%{x},
  {y}, {z} &f»  %design_clr_primary%(%design_clr_main%%time%%design_clr_primary%)'
portals:
  raidInPortal:
    paste:
      schem: raidPortal
      type: default # default припрутить кастомный сапплаер, который в зависимости от типа который тут указан выбирает способ создания обьекта
      pasteStrategy: default # 2 стратегии, Partition Normal. Если Partition -> то new PartitionPaster, по умолчанию Normal
      pasteLocation:
        strategy: async # AsyncLocationFinder.newBuilder -- если не координаты null, если не null то воспользоваться функциональным интерфейсов LocationFinder -> return new location( x y z)
    holo: portalIn
    teleportRadius: 3
    holoOffset:
      x: 0
      y: 10
      z: 0
    portalEntranceOffset:
      x: 0
      y: 8
      z: 0
  raidOutPortal:
    paste:
      schem: portalOut
      type: default # default припрутить кастомный сапплаер, который в зависимости от типа который тут указан выбирает способ создания обьекта
      pasteStrategy: default # 2 стратегии, Partition Normal. Если Partition -> то new PartitionPaster, по умолчанию Normal
      pasteLocation:
        strategy: prepared # AsyncLocationFinder.newBuilder -- если не координаты null, если не null то воспользоваться функциональным интерфейсов LocationFinder -> return new location( x y z)
        world: raidWorld # если null то world
        x: -11.5 # если x,y,z = null то рандомные координаты (метод)
        y: -2 # если x,y,z = null то рандомные координаты (метод)
        z: -11.5 # если x,y,z = null то рандомные координаты (метод)
    holo: portalOut # имя голограммы которая будет взята с другого конфига
    teleportRadius: 3
    holoOffset:
      x: 0
      y: 2
      z: 0
    portalEntranceOffset:
      x: 0
      y: 0
      z: 0
event: # в секундах
  # interval: 3600 #1 час
  interval: 3600 # 1 час
events: # в секундах
  raidworld:
    duration: 1200 # 20 мин
    paste:
      schem: raidWorld
      type: RAIDWORLD # default припрутить кастомный сапплаер, который в зависимости от типа который тут указан выбирает способ создания обьекта
      pasteStrategy: Partition # 2 стратегии, Partition Normal. Если Partition -> то new PartitionPaster, по умолчанию Normal
      partition: # только для Partition
        chunks: 4
        delay: 120 # В тиках (4 секунды)
      pasteLocation:
        strategy: prepared # AsyncLocationFinder.newBuilder -- если не координаты null, если не null то воспользоваться функциональным интерфейсов LocationFinder -> return new location( x y z)
        world: raidWorld # если null то world
        x: 0 # если x,y,z = null то рандомные координаты (метод)
        y: 0 # если x,y,z = null то рандомные координаты (метод)
        z: 0 # если x,y,z = null то рандомные координаты (метод)
    time-to-death: 30 # Время до смерти после окончания события (в секундах)
# Сообщения
messages:
  no-commands:
    enable: true
    text:
      - ' '
      - '%design_clr_primary%Команды в рейде %design_clr_main%отключены.'
      - ' '
  already-met:
    enable: true
    text:
      - ' '
      - '%design_clr_primary%Рейд можно посетить только %design_clr_main%1 раз.'
      - ' '
  time-to-death:
    enable: true
    text:
      - ' '
      - '%design_clr_primary%У вас осталось %design_clr_main%{time} секунд%design_clr_primary%,
      чтобы покинуть рейд!'
      - '%design_clr_primary%Используйте %design_clr_main%энд-портал в центре карты
      %design_clr_primary%для выхода!'
      - ' '
  event-start:
    enable: true
    text:
      - ' '
      - '  %img_miner3% %design_clr_main%Рейдовый мир появился'
      - '             %design_clr_primary%Координаты портала %design_clr_main%{location}'
      - '             %design_clr_primary%Выход только %design_clr_main%через обратный
      портал'
      - '             %design_clr_main%Команды отключены'
      - ' '
  event-end:
    enable: true
    text:
      - ' '
      - '  %img_miner3% %design_clr_main% Рейд закончен. Топ игроков: '
      - '{players}'
  event-end-empty:
    enable: true
    text:
      - ' '
      - '  %img_miner3% %design_clr_main% Рейд закончен.'
      - '%design_clr_primary%             Никто не выбрался живым...'
      - ' '
      - ' '
  event-end-bonus:
    variables: #todo обернуть это все в тег place
      1: "первое место"
      2: "второе место"
      3: "третье место"
      other: "участие"
    enable: true
    text:
      - ' '
      - '  %design_clr_primary%Вы вынесли с рейда &f&r%img_money%%design_clr_money%{raid_amount}'
      - '  %design_clr_primary%Вам выдана награда &f&r%img_donate-icon%%design_clr_donat-money%{bonus_amount}%design_clr_primary% за %design_clr_main%{place}'
      - ' '
  event-announce-5min:
    enable: true
    text:
      - ' '
      - '%design_clr_primary%Рейд начнется через %design_clr_main%5 минут!'
      - ' '
### SCHEDULER
  scheduler-disabled:
    enable: true
    text:
      - ' &cПланировщик событий в данный момент остановлен.'
  scheduler-empty:
    enable: true
    text:
      - ' &cВ очереди нет запланированных событий.'
  scheduler-error-null:
    enable: true
    text:
      - ' &cОшибка: следующее событие повреждено (null).'

  # Когда событие уже идет
  scheduler-info-running:
    enable: true
    text:
      - ' '
      - '  %design_clr_primary%Сейчас идет событие!'
      - '  %design_clr_primary%До следующего (%design_clr_main%{next_event}%design_clr_primary%): &b{time} сек.'
      - ' '

  # Когда сервер просто ожидает запуска следующего события
  scheduler-info-waiting:
    enable: true
    text:
      - ' '
      - '  %design_clr_primary%Следующее событие (%design_clr_main%{next_event}%design_clr_primary%) начнется через: &b{time} сек.'
      - ' '

# Точки спавна игроков в эвентовом мире
playerRespawns:
  - x: -33
    y: -15
    z: 0
  - x: -9
    y: -15
    z: -30
  - x: 18
    y: 2
    z: -32
  - x: -52
    y: 5
    z: 25
  - x: 1
    y: 19
    z: 67
  - x: 63
    y: 13
    z: 41
  - x: 52
    y: 49
    z: 4
  - x: 26
    y: 24
    z: -33
  - x: 8
    y: -3
    z: -10

# Сундуки в эвентовом мире
chests:
  - x: 2
    y: -11
    z: -30
  - x: 15
    y: -11
    z: -26
  - x: 31
    y: 1
    z: -34
  - x: 34
    y: 1
    z: -12
  - x: 29
    y: 1
    z: 12
  - x: 63
    y: 0
    z: 24
  - x: 74
    y: 0
    z: 14
  - x: 68
    y: -3
    z: 1
  - x: 47
    y: 1
    z: 31
  - x: 38
    y: 14
    z: 30
  - x: 38
    y: 14
    z: 14
  - x: 33
    y: 25
    z: 22
  - x: 33
    y: 37
    z: 28
  - x: 42
    y: 37
    z: 21
  - x: 20
    y: 37
    z: 29
  - x: 21
    y: 37
    z: 20
  - x: 22
    y: 49
    z: 25
  - x: 22
    y: 49
    z: 19
  - x: 40
    y: 49
    z: 22
  - x: 52
    y: 49
    z: -7
  - x: 26
    y: 57
    z: -24
  - x: -33
    y: 47
    z: -10
  - x: -12
    y: 51
    z: 34
  - x: 23
    y: 24
    z: -28
  - x: 29
    y: 12
    z: -35
  - x: 10
    y: -15
    z: -10
  - x: -21
    y: -15
    z: -29
  - x: -53
    y: 41
    z: -7
  - x: -45
    y: 49
    z: -9
  - x: 4
    y: -4
    z: -60

# Лут для сундуков
loot:
  - material: DIAMOND
    amount-min: 1
    amount-max: 3
  - material: GOLD_INGOT
    amount-min: 5
    amount-max: 10
  - material: IRON_INGOT
    amount-min: 10
    amount-max: 20
  - material: EMERALD
    amount-min: 2
    amount-max: 5
  - material: DIAMOND_SWORD
    amount: 1
  - material: DIAMOND_PICKAXE
    amount: 1
  - material: GOLDEN_APPLE
    amount-min: 1
    amount-max: 3
  - material: ENCHANTED_BOOK
    amount: 1
